
CREATE TABLE CUSTOMER(
	ID [bigint] IDENTITY(1,1) NOT NULL,
	FIRSTNAME [varchar](50) NOT NULL,
	LASTNAME [varchar](50) NOT NULL,
	CONTACTNUMBER [varchar](50) NOT NULL 
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE EMPLOYEE(
	ID [bigint] IDENTITY(1,1) NOT NULL,
	FIRSTNAME [varchar](50) NOT NULL,
	LASTNAME [varchar](50) NOT NULL,
	CONTACTNUMBER [varchar](50) NOT NULL,
	ISADMIN BIT,
	VEHICLENAME [varchar](50) NOT NULL
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE TRIP(
	ID [bigint] IDENTITY(1,1) NOT NULL,
	SOURCE [varchar](50) NOT NULL,
	DESTINATION [varchar](50) NOT NULL,
	EMPLOYEEID BIGINT NOT NULL,
	CUSTOMERID BIGINT NOT NULL,
	VEHICLENAME [varchar](50) NOT NULL,
	STATUS BIT
 CONSTRAINT [PK_TRIP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE TRIP  WITH CHECK ADD  CONSTRAINT [FK_TRIP_CUSTOMERID1] FOREIGN KEY(CUSTOMERID)
REFERENCES [CUSTOMER] (ID)
GO
ALTER TABLE TRIP  WITH CHECK ADD  CONSTRAINT [FK_TRIP_EMPLOYEEID2] FOREIGN KEY(EMPLOYEEID)
REFERENCES EMPLOYEE (ID)
GO



INSERT INTO  CUSTOMER (FIRSTNAME, LASTNAME, CONTACTNUMBER) VALUES ('RAHUL',  'SHARMA', '7894521300'), ('ISHAN',  'KRISH', '9145678921'), ('SHERIN',  'KRISH', '9865321470')
INSERT INTO  EMPLOYEE (FIRSTNAME, LASTNAME, CONTACTNUMBER, ISADMIN, VEHICLENAME) VALUES 
('PRABU',  'SHIVAN', '9856521300', 1, 'TN 07 CB 1287'), 
('PRAVIN',  'SAAI', '9874512630', 0, 'TN 27 TB 6587'), 
('SHERIN',  'KRISH', '9865741230', 0, 'TN 13 CN 7521')
GO
INSERT INTO  TRIP (SOURCE, DESTINATION, EMPLOYEEID, CUSTOMERID, VEHICLENAME, STATUS) VALUES 
('VLCY', 'TMBRM', 2, 1, '', 1),
('PORUR', 'OMR', 1, 3, '', 0)
